import * as childProcess from "child_process";
import { writeFileSync } from "fs";
import { dedent } from "tslint/lib/utils";
import * as util from "util";

const exec = util.promisify(childProcess.exec);

const createVersionsFile = async (filename: string) => {
  const revision = (await exec("git rev-parse --short HEAD")).stdout
    .toString()
    .trim();
  const branch = (await exec("git rev-parse --abbrev-ref HEAD")).stdout
    .toString()
    .trim();

  console.log(
    `version: "${
      process.env.npm_package_version
    }", revision: "${revision}", branch: "${branch}"`
  );

  const content = dedent`// this file is automatically generated by git-version.ts script
      export const version = {
        version: "${process.env.npm_package_version}",
        revision: "${revision}",
        branch: "${branch}"
      };`;

  writeFileSync(filename, content, { encoding: "utf8" });
};

createVersionsFile("version.ts");
