//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System.Xml.Serialization;

namespace LivestreamApp.Server.Streaming.StreamingSessions.Entities
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "SessionsConfigXsd")]
    [XmlRoot("Sessions", Namespace = "SessionsConfigXsd", IsNullable = false)]
    public partial class SessionsType
    {

        private SessionType[] _sessionsField;

        /// <remarks/>
        [XmlElement("Session")]
        public SessionType[] Sessions
        {
            get
            {
                return this._sessionsField;
            }
            set
            {
                this._sessionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "SessionsConfigXsd")]
    public partial class SessionType
    {

        private string idField;

        private string titleField;

        private string internalTitleField;

        private string descriptionField;

        private System.DateTime timeStartingField;

        private bool timeStartingFieldSpecified;

        private System.DateTime timeEndingField;

        private bool timeStoppingFieldSpecified;

        private System.DateTime timeServerShutdownField;

        private bool timeServerShutdownFieldSpecified;

        private string[] streamsField;

        /// <remarks/>
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string InternalTitle
        {
            get
            {
                return this.internalTitleField;
            }
            set
            {
                this.internalTitleField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "time")]
        public System.DateTime TimeStarting
        {
            get
            {
                return this.timeStartingField;
            }
            set
            {
                this.timeStartingField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool TimeStartingSpecified
        {
            get
            {
                return this.timeStartingFieldSpecified;
            }
            set
            {
                this.timeStartingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "time")]
        public System.DateTime TimeEnding
        {
            get
            {
                return this.timeEndingField;
            }
            set
            {
                this.timeEndingField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool TimeEndingSpecified
        {
            get
            {
                return this.timeStoppingFieldSpecified;
            }
            set
            {
                this.timeStoppingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "time")]
        public System.DateTime TimeServerShutdown
        {
            get
            {
                return this.timeServerShutdownField;
            }
            set
            {
                this.timeServerShutdownField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool TimeServerShutdownSpecified
        {
            get
            {
                return this.timeServerShutdownFieldSpecified;
            }
            set
            {
                this.timeServerShutdownFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("StreamId", IsNullable = false)]
        public string[] Streams
        {
            get
            {
                return this.streamsField;
            }
            set
            {
                this.streamsField = value;
            }
        }
    }
}
