//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 
namespace LivestreamService.Server.Entities
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "LiveStreamsConfigXsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "LiveStreamsConfigXsd", IsNullable = false)]
    public partial class LiveStreamsType
    {

        private LiveStreamsTypeLiveStreamType[] liveStreamTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LiveStreamType")]
        public LiveStreamsTypeLiveStreamType[] LiveStreamType
        {
            get
            {
                return this.liveStreamTypeField;
            }
            set
            {
                this.liveStreamTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "LiveStreamsConfigXsd")]
    public partial class LiveStreamsTypeLiveStreamType
    {

        private string idField;

        private string titleField;

        private string countryCodeField;

        private string descriptionField;

        private string audioInputField;

        private bool startOnServiceStartupField;

        /// <remarks/>
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string AudioInput
        {
            get
            {
                return this.audioInputField;
            }
            set
            {
                this.audioInputField = value;
            }
        }

        /// <remarks/>
        public bool StartOnServiceStartup
        {
            get
            {
                return this.startOnServiceStartupField;
            }
            set
            {
                this.startOnServiceStartupField = value;
            }
        }
    }
}
