//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System.Xml.Serialization;

namespace LivestreamApp.Server.Streaming.Sessions.Entities
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "StreamingSessionsConfigXsd")]
    [XmlRoot("StreamingSessions", Namespace = "StreamingSessionsConfigXsd", IsNullable = false)]
    public partial class StreamingSessionsType
    {

        private StreamingSessionType[] _streamingSessionsField;

        /// <remarks/>
        [XmlElement("StreamingSession")]
        public StreamingSessionType[] StreamingSessions
        {
            get
            {
                return this._streamingSessionsField;
            }
            set
            {
                this._streamingSessionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "StreamingSessionsConfigXsd")]
    public partial class StreamingSessionType
    {

        private string idField;

        private string titleField;

        private System.DateTime timeStartingField;

        private bool timeStartingFieldSpecified;

        private System.DateTime timeStoppingField;

        private bool timeStoppingFieldSpecified;

        private System.DateTime timeServerShutdownField;

        private bool timeServerShutdownFieldSpecified;

        private string[] livestreamsField;

        /// <remarks/>
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "time")]
        public System.DateTime TimeStarting
        {
            get
            {
                return this.timeStartingField;
            }
            set
            {
                this.timeStartingField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool TimeStartingSpecified
        {
            get
            {
                return this.timeStartingFieldSpecified;
            }
            set
            {
                this.timeStartingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "time")]
        public System.DateTime TimeStopping
        {
            get
            {
                return this.timeStoppingField;
            }
            set
            {
                this.timeStoppingField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool TimeStoppingSpecified
        {
            get
            {
                return this.timeStoppingFieldSpecified;
            }
            set
            {
                this.timeStoppingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "time")]
        public System.DateTime TimeServerShutdown
        {
            get
            {
                return this.timeServerShutdownField;
            }
            set
            {
                this.timeServerShutdownField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool TimeServerShutdownSpecified
        {
            get
            {
                return this.timeServerShutdownFieldSpecified;
            }
            set
            {
                this.timeServerShutdownFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("LivestreamId", IsNullable = false)]
        public string[] Livestreams
        {
            get
            {
                return this.livestreamsField;
            }
            set
            {
                this.livestreamsField = value;
            }
        }
    }
}
