//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 
namespace LivestreamApp.Server.Streaming.Streams.Entities
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "LivestreamsConfigXsd")]
    [System.Xml.Serialization.XmlRootAttribute("LiveStreams", Namespace = "LivestreamsConfigXsd", IsNullable = false)]
    public partial class LivestreamsType
    {

        private LivestreamType[] _liveStreamsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LiveStream")]
        public LivestreamType[] LiveStreams
        {
            get
            {
                return this._liveStreamsField;
            }
            set
            {
                this._liveStreamsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "LivestreamsConfigXsd")]
    public partial class LivestreamType
    {

        private string idField;

        private string titleField;

        private string countryCodeField;

        private string descriptionField;

        private string inputSourceField;

        private bool startOnServiceStartupField;

        /// <remarks/>
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string InputSource
        {
            get
            {
                return this.inputSourceField;
            }
            set
            {
                this.inputSourceField = value;
            }
        }

        /// <remarks/>
        public bool StartOnServiceStartup
        {
            get
            {
                return this.startOnServiceStartupField;
            }
            set
            {
                this.startOnServiceStartupField = value;
            }
        }
    }
}
